#!/usr/bin/env python
# -*- coding: utf-8 -*-

import socket
import ev3dev.ev3 as ev3
import time

host = '192.168.245.79' # IP-address to computer
port = 12345            # Port the server is listening to

s = socket.socket()
s.connect((host, port))

s.send("EV3 is ready")
data = s.recv(1024)
command = data.strip()

print ("Received:", command)

leftMotor = ev3.LargeMotor('outA')
rightMotor = ev3.LargeMotor('outB')
smallMotor = ev3.MediumMotor('outC')

if command == "drive":
    print "Driving forward for 2 seconds"
    leftMotor.run_forever(speed_sp=-500)
    rightMotor.run_forever(speed_sp=-500)
    time.sleep(2)
    leftMotor.stop()
    rightMotor.stop()
elif command == "grab":
    smallMotor.run_forever(speed_sp=250)
    time.sleep(2)
    smallMotor.stop()
else:
    print "Unknown command:", command

s.close()
